# Generated by Django 3.2.4 on 2021-06-04 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gate_Master',
            fields=[
                ('Gate_ID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Gate_Name', models.CharField(max_length=50)),
                ('Updated_Date', models.DateField()),
                ('Updated_By', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Institution_Master',
            fields=[
                ('Institution_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Institution_Name', models.CharField(max_length=100)),
                ('Updated_Date', models.DateField()),
                ('Updated_By', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Member_Category_Master',
            fields=[
                ('Member_Category_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Member_Category', models.CharField(max_length=50)),
                ('Updated_Date', models.DateField()),
                ('Updated_By', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Member_Master',
            fields=[
                ('Member_PRANAMS_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Member_Name', models.CharField(max_length=100)),
                ('Member_Photo_File_Name', models.CharField(max_length=150)),
                ('Member_Type', models.CharField(max_length=20)),
                ('Member_Aadhaar_ID', models.IntegerField()),
                ('Member_Photo', models.CharField(max_length=20)),
                ('Member_DOB', models.DateField()),
                ('Member_Mobile', models.IntegerField()),
                ('Member_Whatsapp', models.IntegerField()),
                ('Member_Blood_Group', models.CharField(max_length=10)),
                ('Staff_Designation', models.CharField(max_length=20)),
                ('Staff_Working_Since', models.DateField()),
                ('Staff_Institutuon_Emp_ID', models.CharField(max_length=20)),
                ('Updated_Date', models.DateField()),
                ('Updated_By', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=1)),
                ('Address_Outside_PSN', models.CharField(max_length=200)),
                ('Emergency_Contact_Name', models.CharField(max_length=40)),
                ('Emergency_Contact_Email', models.CharField(max_length=40)),
                ('Emergency_Contact_Relationship', models.CharField(max_length=20)),
                ('Emergency_Contact_ISD', models.CharField(max_length=20)),
                ('Emergency_Contact_Mobile_No', models.IntegerField()),
                ('Emergency_Contact_Address', models.CharField(max_length=200)),
                ('Member_DL_No', models.CharField(max_length=50)),
                ('Member_DL_Validity', models.DateField()),
                ('Member_Category_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PranamsApp.member_category_master')),
                ('Staff_Institution_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PranamsApp.institution_master')),
            ],
        ),
        migrations.CreateModel(
            name='Occupant_Master',
            fields=[
                ('Occ_Name', models.CharField(max_length=100)),
                ('Occ_DOB', models.DateField()),
                ('Occ_Relationship', models.CharField(max_length=20)),
                ('Occ_Permanent_Resident_Not', models.CharField(max_length=1)),
                ('Occ_Aadhaar_ID', models.IntegerField()),
                ('Occupant_PRANAMS_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Occ_DL_No', models.CharField(max_length=50)),
                ('Updated_Date', models.DateField()),
                ('Updated_By', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=1)),
                ('Member_PRANAMS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PranamsApp.member_master')),
            ],
        ),
        migrations.CreateModel(
            name='Room_Type_Master',
            fields=[
                ('Room_Type_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Room_Type_Desc', models.CharField(max_length=20)),
                ('Updated_Date', models.DateField()),
                ('Updated_By', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Division_Master',
            fields=[
                ('Sub_Division_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Sub_Division_Name', models.CharField(max_length=100)),
                ('Updated_Date', models.DateField()),
                ('Updated_By', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_Master',
            fields=[
                ('Vehicle_PRANAMS_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Vehicle_No', models.CharField(max_length=20)),
                ('Two_Four_Wheeler', models.CharField(max_length=1)),
                ('RC_No', models.CharField(max_length=30)),
                ('RC_Valid_Upto', models.DateField()),
                ('Insurance_Valid_Upto', models.DateField()),
                ('Entry_Extended_By', models.CharField(max_length=30)),
                ('Remarks', models.CharField(max_length=200)),
                ('Updated_Date', models.DateField()),
                ('Updated_By', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=1)),
                ('Member_PRANAMS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PranamsApp.member_master')),
                ('Occupant_PRANAMS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PranamsApp.occupant_master')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_Gate_Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Updated_Date', models.DateField()),
                ('Updated_By', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=1)),
                ('Gate_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PranamsApp.gate_master')),
                ('Vehicle_PRANAMS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PranamsApp.vehicle_master')),
            ],
        ),
        migrations.CreateModel(
            name='Room_Master',
            fields=[
                ('Room', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Updated_Date', models.DateField()),
                ('Updated_By', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=1)),
                ('Room_Type_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PranamsApp.room_type_master')),
            ],
        ),
        migrations.AddField(
            model_name='member_master',
            name='Staff_Sub_Division_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PranamsApp.sub_division_master'),
        ),
        migrations.CreateModel(
            name='Member_Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Updated_Date', models.DateField()),
                ('Updated_By', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=1)),
                ('Member_PRANAMS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PranamsApp.member_master')),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PranamsApp.room_master')),
            ],
        ),
        migrations.CreateModel(
            name='Institution_Sub_Division_Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Updated_Date', models.DateField()),
                ('Updated_By', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=1)),
                ('Institution_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PranamsApp.institution_master')),
                ('Sub_Division_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PranamsApp.sub_division_master')),
            ],
        ),
    ]
