# Generated by Django 3.2.4 on 2021-07-04 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PranamsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_demography',
            old_name='Member_Mobile',
            new_name='Mobile',
        ),
        migrations.RenameField(
            model_name='add_demography',
            old_name='Member_Name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='add_demography',
            old_name='Member_Photo_File_Name',
            new_name='Photo_File_Name',
        ),
        migrations.RenameField(
            model_name='add_demography',
            old_name='Member_Whatsapp',
            new_name='Whatsapp',
        ),
        migrations.RemoveField(
            model_name='add_demography',
            name='Member_Aadhaar_ID',
        ),
        migrations.RemoveField(
            model_name='add_demography',
            name='Member_Blood_Group',
        ),
        migrations.RemoveField(
            model_name='add_demography',
            name='Member_Category',
        ),
        migrations.RemoveField(
            model_name='add_demography',
            name='Member_DOB',
        ),
        migrations.AddField(
            model_name='add_demography',
            name='Aadhaar_ID',
            field=models.IntegerField(blank=True, default=147852369874),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_demography',
            name='Blood_Group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('O+', 'O+'), ('O-', 'O-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3),
        ),
        migrations.AddField(
            model_name='add_demography',
            name='Category',
            field=models.ForeignKey(blank=True, default='PRS', on_delete=django.db.models.deletion.CASCADE, to='PranamsApp.member_category_master'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_demography',
            name='DOB',
            field=models.DateField(blank=True, default='2001-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_demography',
            name='Member_Occupant',
            field=models.CharField(choices=[('member', 'Member'), ('occupant', 'Occupant')], default='Member', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_demography',
            name='Permanent_Resident_Or_Not',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=5),
        ),
        migrations.AddField(
            model_name='add_demography',
            name='Relationship_With_Primary_Member',
            field=models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('spouse', 'Spouse'), ('son', 'Son'), ('daughter', 'Daughter'), ('brother', 'Brother'), ('sister', 'Sister'), ('grandSon', 'Grand Son'), ('grandDaughter', 'Grand Daughter'), ('niece', 'Niece'), ('nephew', 'Nephew'), ('colleague', 'Colleague'), ('others', 'Others')], default='Father', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Member_Accommodation',
        ),
    ]
