# Generated by Django 3.2.4 on 2021-07-04 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PranamsApp', '0002_auto_20210705_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_demography',
            name='Room_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PranamsApp.room_type_master'),
        ),
    ]
