# Generated by Django 3.2.4 on 2021-07-05 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PranamsApp', '0003_alter_add_demography_room_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle_Gate_Map',
        ),
    ]
