# Generated by Django 3.2.4 on 2021-07-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PranamsApp', '0004_delete_vehicle_gate_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_demography',
            name='Photo_File_Name',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='add_demography',
            name='Staff_Working_Since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='add_demography',
            name='Whatsapp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
