# Generated by Django 3.2.4 on 2021-07-05 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PranamsApp', '0005_auto_20210705_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_demography',
            name='Aadhaar_ID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='add_demography',
            name='Address_Outside_PSN',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='add_demography',
            name='Blood_Group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('O+', 'O+'), ('O-', 'O-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='add_demography',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PranamsApp.member_category_master'),
        ),
        migrations.AlterField(
            model_name='add_demography',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='add_demography',
            name='Institution_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PranamsApp.institution_master'),
        ),
        migrations.AlterField(
            model_name='add_demography',
            name='Mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='add_demography',
            name='Permanent_Resident_Or_Not',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='add_demography',
            name='Relationship_With_Primary_Member',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('spouse', 'Spouse'), ('son', 'Son'), ('daughter', 'Daughter'), ('brother', 'Brother'), ('sister', 'Sister'), ('grandSon', 'Grand Son'), ('grandDaughter', 'Grand Daughter'), ('niece', 'Niece'), ('nephew', 'Nephew'), ('colleague', 'Colleague'), ('others', 'Others')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='add_demography',
            name='Room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PranamsApp.room_master'),
        ),
        migrations.AlterField(
            model_name='add_demography',
            name='Room_Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PranamsApp.room_type_master'),
        ),
        migrations.AlterField(
            model_name='add_demography',
            name='Staff_Designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='add_demography',
            name='Staff_Institution_Emp_ID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='add_demography',
            name='Sub_Division_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PranamsApp.sub_division_master'),
        ),
        migrations.AlterField(
            model_name='add_demography',
            name='Whatsapp_Choice',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=5, null=True),
        ),
    ]
