# Generated by Django 3.2.4 on 2021-07-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PranamsApp', '0006_auto_20210705_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_demography',
            name='Emergency_Contact_Address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='add_demography',
            name='Emergency_Contact_Email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='add_demography',
            name='Emergency_Contact_ISD',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='add_demography',
            name='Emergency_Contact_Mobile_No',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='add_demography',
            name='Emergency_Contact_Name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='add_demography',
            name='Emergency_Contact_Relationship',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('spouse', 'Spouse'), ('son', 'Son'), ('daughter', 'Daughter'), ('brother', 'Brother'), ('sister', 'Sister'), ('grandSon', 'Grand Son'), ('grandDaughter', 'Grand Daughter'), ('niece', 'Niece'), ('nephew', 'Nephew'), ('colleague', 'Colleague'), ('others', 'Others')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='add_demography',
            name='Photo_File_Name',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
