# Generated by Django 3.2.4 on 2021-07-08 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PranamsApp', '0007_auto_20210705_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_vehicle',
            name='Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PranamsApp.add_demography'),
        ),
        migrations.CreateModel(
            name='Vehicle_Gate_Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Updated_Date', models.DateField()),
                ('Updated_By', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=1)),
                ('Gate_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PranamsApp.gate_master')),
                ('Vehicle_PRANAMS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PranamsApp.add_vehicle')),
            ],
        ),
    ]
