# Generated by Django 3.2.4 on 2021-07-08 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PranamsApp', '0008_auto_20210708_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_vehicle',
            old_name='Name',
            new_name='Member_Name',
        ),
    ]
