# Generated by Django 3.2.4 on 2021-07-09 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PranamsApp', '0009_rename_name_add_vehicle_member_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member_master',
            name='Address_Outside_PSN',
        ),
        migrations.RemoveField(
            model_name='member_master',
            name='Emergency_Contact_Address',
        ),
        migrations.RemoveField(
            model_name='member_master',
            name='Emergency_Contact_Email',
        ),
        migrations.RemoveField(
            model_name='member_master',
            name='Emergency_Contact_ISD',
        ),
        migrations.RemoveField(
            model_name='member_master',
            name='Emergency_Contact_Mobile_No',
        ),
        migrations.RemoveField(
            model_name='member_master',
            name='Emergency_Contact_Name',
        ),
        migrations.RemoveField(
            model_name='member_master',
            name='Emergency_Contact_Relationship',
        ),
        migrations.RemoveField(
            model_name='member_master',
            name='Member_Aadhaar_ID',
        ),
        migrations.RemoveField(
            model_name='member_master',
            name='Member_Blood_Group',
        ),
        migrations.RemoveField(
            model_name='member_master',
            name='Member_DOB',
        ),
        migrations.RemoveField(
            model_name='member_master',
            name='Member_Mobile',
        ),
        migrations.RemoveField(
            model_name='member_master',
            name='Member_Photo_File_Name',
        ),
        migrations.RemoveField(
            model_name='member_master',
            name='Member_Whatsapp',
        ),
        migrations.RemoveField(
            model_name='member_master',
            name='Room',
        ),
        migrations.RemoveField(
            model_name='member_master',
            name='Staff_Designation',
        ),
        migrations.RemoveField(
            model_name='member_master',
            name='Staff_Working_Since',
        ),
        migrations.AlterField(
            model_name='add_vehicle',
            name='Member_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PranamsApp.member_master'),
        ),
    ]
