# Generated by Django 3.2.4 on 2021-07-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PranamsApp', '0010_auto_20210709_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_master',
            name='Occupant_Member',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='member_master',
            name='Member_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member_master',
            name='Status',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='member_master',
            name='Updated_By',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='member_master',
            name='Updated_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Occupant_Master',
        ),
    ]
