# Generated by Django 3.2.4 on 2021-07-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PranamsApp', '0011_auto_20210710_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_master',
            name='Member_PRANAMS_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
