# Generated by Django 3.2.4 on 2021-07-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PranamsApp', '0012_alter_member_master_member_pranams_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle_Gate_Map',
        ),
    ]
