# Generated by Django 3.2.4 on 2021-07-10 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PranamsApp', '0014_alter_add_vehicle_member_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member_Master',
        ),
    ]
