# Generated by Django 3.2.4 on 2021-07-15 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PranamsApp', '0015_delete_member_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_maid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Maid_ID', models.IntegerField(blank=True, null=True)),
                ('Maid_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Relation', models.CharField(blank=True, choices=[('wo', 'W/O'), ('do', 'D/O'), ('so', 'S/O')], max_length=5, null=True)),
                ('Relation_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('NightDuty_Permitted', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('Year_Of_Birth', models.IntegerField(blank=True, null=True)),
                ('Aadhaar_ID', models.IntegerField()),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('Address_Outside_PSN', models.CharField(blank=True, max_length=200, null=True)),
                ('Remarks', models.CharField(max_length=200)),
                ('Updated_Date', models.DateTimeField(auto_now_add=True)),
                ('Updated_By', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=1)),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PranamsApp.room_master')),
            ],
        ),
    ]
