# Generated by Django 3.2.4 on 2021-07-15 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PranamsApp', '0016_add_maid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_demography',
            name='Emergency_Contact_Address',
        ),
        migrations.RemoveField(
            model_name='add_demography',
            name='Emergency_Contact_Email',
        ),
        migrations.RemoveField(
            model_name='add_demography',
            name='Emergency_Contact_ISD',
        ),
        migrations.RemoveField(
            model_name='add_demography',
            name='Emergency_Contact_Mobile_No',
        ),
        migrations.RemoveField(
            model_name='add_demography',
            name='Emergency_Contact_Name',
        ),
        migrations.RemoveField(
            model_name='add_demography',
            name='Emergency_Contact_Relationship',
        ),
        migrations.RemoveField(
            model_name='add_demography',
            name='Staff_Designation',
        ),
        migrations.AddField(
            model_name='add_demography',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_demography',
            name='Landline_Number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='add_maid',
            name='Status',
            field=models.CharField(default='Y', max_length=2),
        ),
        migrations.AlterField(
            model_name='add_maid',
            name='Updated_By',
            field=models.CharField(default='Admin', max_length=10),
        ),
        migrations.AlterField(
            model_name='add_vehicle',
            name='Status',
            field=models.CharField(default='Y', max_length=2),
        ),
        migrations.AlterField(
            model_name='add_vehicle',
            name='Updated_By',
            field=models.CharField(default='Admin', max_length=10),
        ),
        migrations.CreateModel(
            name='add_emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emergency_Contact_Name', models.CharField(blank=True, max_length=40, null=True)),
                ('Emergency_Contact_Email', models.CharField(blank=True, max_length=40, null=True)),
                ('Emergency_Contact_Relationship', models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('spouse', 'Spouse'), ('son', 'Son'), ('daughter', 'Daughter'), ('brother', 'Brother'), ('sister', 'Sister'), ('grandSon', 'Grand Son'), ('grandDaughter', 'Grand Daughter'), ('niece', 'Niece'), ('nephew', 'Nephew'), ('colleague', 'Colleague'), ('others', 'Others')], max_length=20, null=True)),
                ('Emergency_Contact_ISD', models.CharField(blank=True, max_length=20, null=True)),
                ('Emergency_Contact_Mobile_No', models.IntegerField(blank=True, null=True)),
                ('Emergency_Contact_Address', models.CharField(blank=True, max_length=200, null=True)),
                ('Updated_Date', models.DateTimeField(auto_now_add=True)),
                ('Updated_By', models.CharField(default='Admin', max_length=10)),
                ('Status', models.CharField(default='Y', max_length=2)),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PranamsApp.room_master')),
            ],
        ),
    ]
