# Generated by Django 3.2.4 on 2021-07-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PranamsApp', '0017_auto_20210715_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_demography',
            name='SSSIHMS_PG_Patient_ID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
