# Generated by Django 3.2.4 on 2021-07-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PranamsApp', '0019_add_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_demography',
            name='Remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
