# Generated by Django 3.2.4 on 2021-07-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PranamsApp', '0020_add_demography_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_vehicle',
            name='Vehicle_Available',
        ),
        migrations.AlterField(
            model_name='add_demography',
            name='Remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
