# Generated by Django 3.2.4 on 2021-07-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PranamsApp', '0021_auto_20210715_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_vehicle',
            name='RC_No',
        ),
        migrations.AddField(
            model_name='add_vehicle',
            name='Existing_Sticker_Number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
