# Generated by Django 3.2.4 on 2021-07-15 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PranamsApp', '0022_auto_20210715_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_demography',
            name='Permanent_Resident_Or_Not',
        ),
    ]
