# Generated by Django 3.2.4 on 2021-07-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PranamsApp', '0023_remove_add_demography_permanent_resident_or_not'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_demography',
            name='Address_Outside_PSN',
        ),
        migrations.AddField(
            model_name='add_maid',
            name='Validity',
            field=models.DateField(blank=True, null=True, verbose_name='Maid Validity in YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='add_demography',
            name='DOB',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth in YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='add_demography',
            name='Staff_Working_Since',
            field=models.DateField(blank=True, null=True, verbose_name='Staff Working Since in YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='add_vehicle',
            name='DL_Validity',
            field=models.DateField(verbose_name='DL Valid Upto in YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='add_vehicle',
            name='Insurance_Valid_Upto',
            field=models.DateField(verbose_name='Insurance Valid Upto in YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='add_vehicle',
            name='RC_Valid_Upto',
            field=models.DateField(verbose_name='RC Valid Upto in YYYY-MM-DD'),
        ),
    ]
