# Generated by Django 3.2.4 on 2021-07-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PranamsApp', '0024_auto_20210715_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_demography',
            name='Aadhaar_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='add_demography',
            name='Member_Occupant',
            field=models.CharField(choices=[('member', 'Staff'), ('occupant', 'Occupant')], max_length=15, verbose_name='Is the resident a Staff/ Not?'),
        ),
        migrations.AlterField(
            model_name='add_maid',
            name='Remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='add_vehicle',
            name='Member_Occupant',
            field=models.CharField(choices=[('member', 'Staff'), ('occupant', 'Occupant')], max_length=15),
        ),
    ]
