# Generated by Django 3.2.4 on 2021-07-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PranamsApp', '0025_auto_20210719_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_demography',
            name='Member_Occupant',
            field=models.CharField(choices=[('member', 'Staff'), ('occupant', 'Occupant')], max_length=15, verbose_name='Is the Occupant a Staff/ Not?'),
        ),
        migrations.AlterField(
            model_name='add_vehicle',
            name='DL_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='add_vehicle',
            name='DL_Validity',
            field=models.DateField(blank=True, null=True, verbose_name='DL Valid Upto in YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='add_vehicle',
            name='Insurance_Valid_Upto',
            field=models.DateField(blank=True, null=True, verbose_name='Insurance Valid Upto in YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='add_vehicle',
            name='RC_Valid_Upto',
            field=models.DateField(blank=True, null=True, verbose_name='RC Valid Upto in YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='add_vehicle',
            name='Remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
