# Generated by Django 3.2.4 on 2021-07-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PranamsApp', '0026_auto_20210719_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_demography',
            name='Member_Occupant',
            field=models.CharField(blank=True, choices=[('member', 'Staff'), ('occupant', 'Occupant')], max_length=15, null=True, verbose_name='Is the Occupant a Staff/ Not?'),
        ),
    ]
