# Generated by Django 3.2.4 on 2021-07-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PranamsApp', '0027_alter_add_demography_member_occupant'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sticker_Number', models.IntegerField(blank=True, null=True)),
                ('Updated_Date', models.DateTimeField(auto_now_add=True)),
                ('Updated_By', models.CharField(default='Sevadal', max_length=10)),
                ('Status', models.CharField(default='Y', max_length=2)),
            ],
        ),
    ]
